### ISSUE TITLE
Invisible today

### ISSUE THREAD

**Issue by zanozik** [jackyliang/Material-Design-For-Full-Calendar#3]
[_materialFullCalendar.scss](https://github.com/jackyliang/Material-Design-For-Full-Calendar/blob/master/_materialFullCalendar.scss) :40
```
/* Remove that awful yellow color and border from today in Schedule */
.fc-today {
    opacity: 0;
    border: none;
}
```
What is this blasphemy? You are not only removing highlighting for today (which is a must!) - whole cell becomes invisible!

**Comment by jackyliang** [comment]
Hi zanozik. Thanks for raising this concern. For my uses in my project as as general all-purpose class scheduling website, it wasn't necessary to have the today highlighting, since it was a date agnostic. However, for your personal uses, feel free to remove that. That's the point of open source isn't it ;)?
